name: pnpm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        standalone: true  # Install pnpm standalone, without setting up Node.js

    - run: pnpm install
    # - run: pnpm build
    - run: pnpm test
